### ISSUE TITLE
Problem sa generisanjem slike uplatnice

### ISSUE THREAD

**Issue by milanche911** [marlevak/Croatian-payment-slip-generator-for-WooCommerce#14]
Problem koji se desavao je sledeci,

Ukoliko korisnik obavi jednu narudzbinu njemu stigne email sa ispravnom uplatnicom medjutim ukoliko odmah nakon toga odluci da uradi novu narudzbinu za drugi proizvod u mailu mu stigne uplatnica sa podacima iz prethodne narudzbine sto je nama pravilo veliki problem.

Kopajuci malo po kodu video sam da se slika uplatnice cuva u sesiji. 

Wooplatnica.php fajl 83. linija. Nakon te izmene sve je pocelo da radi kako treba.

Tako da mozda mozete ovo ukljuciti kao update ukoliko ne remeti neke druge stvari u pluginu.

**Comment by zeko868** [comment]
Pozdrav,

slika se za sada pohranjuje u sesiju zato što se u klasičnom scenariju pojavljuje 2 puta potreba za slikom s uplatnicom: naime, nakon što korisnik kreira narudžbu, prvo mu se generira slika jer se prilaže u e-mail poruci, a odmah nakon toga mu se očita stranica s detaljima o narudžbi gdje se opet treba prikazati ta slika.

Zbog toga se je kod prve potrebe za slikom ona generira i pohranjuje u sesiju, a par (mili)sekundi kasnije se ona iščitava iz sesije radi prikaza te se tada briše iz nje - na taj način se značajno skraćuje vrijeme koje korisnik mora čekati nakon kreiranja narudžbe za prikaz stranice koja bi ga obavijestila da je uspješno završio proces naručivanja.
Međutim, uočavam da u vašem scenariju se očito ne odrađuje drugi korak u kojem bi se ponovno dohvatila prethodno-pohranjena slika te ujedno obrisala iz sesije.

Stoga, zanima me da li ste kroz kakve postavke WooCommerce-a (ili možda kroz kakav plugin) učinili da se nakon kreiranja narudžbe korisniku ne prikaže klasična stranica s njenim detaljima (tzv. _thankyou_ stranica), već neka druga stranica čime se ne okine filter pretplaćen na _woocommerce_thankyou_woocommerce-croatia_ akciju kojim bi se očitala i obrisala slika iz sesije?

**Comment by milanche911** [comment]
Da to je to, imamo custom thank you page. Pa je verovatno to razlog. OK onda se to moze resiti. Hvala!

**Comment by marlevak** [comment]
Izdana je verzija plugina 1.5.4 u kojoj više ne biste trebali imati problem gdje se korisniku kod naknadnog kreiranja nove narudžbe e-mailom pošalje slika uplatnice koja je vezana uz narudžbu kreiranu za vrijeme trajanje te iste sesije. Commit: 68cd314ef1d6d63392f8f601ac5b12fb430b2cc8

Ujedno je pritom osigurano da se u slučaju poput vašega (gdje koristite custom ThankYou stranicu) vrši brisanje starih slika uplatnica iz sesije (koje su se tamo pohranjivale isključivo radi potrebe optimizacije kao što je spomenuo @zeko868 ) kako bi se rasteretio diskovni prostor kojeg zauzima sesija web-poslužitelja. Commit: 5eaa0b471707d7a1b0459fa4aea52f7cb5f063bb

Tako da biste trebali moći preuzeti novu verziju plugina s Wordpressove administrativne upravljačke ploče, tako da ne trebate ručno dodavati promjene koje ste naveli u svojoj prvoj poruci nakon svakog ažuriranja plugina :)
